"use client";

import { useCallback, useState } from "react";

import { useOrbitPageInteractions } from "@/hooks/use-orbit-page-interactions";
import { useOrbitQueue } from "@/hooks/use-orbit-queue";
import { useOrbitScanSession } from "@/hooks/use-orbit-scan-session";

export type { BookmarkResponse, OrbitScanCandidatesResponse, OrbitScanRequest } from "@/lib/orbit-page-types";

export function useOrbitPage() {
  const [activeBookmarkId, setActiveBookmarkId] = useState<string | null>(null);
  const [selectionMode, setSelectionMode] = useState(false);
  const [selectedBookmarkIds, setSelectedBookmarkIds] = useState<Set<string>>(
    () => new Set()
  );

  const handleUrlStateApplied = useCallback(() => {
    setActiveBookmarkId(null);
    setSelectionMode(false);
    setSelectedBookmarkIds(new Set());
  }, []);

  const queue = useOrbitQueue({ onUrlStateApplied: handleUrlStateApplied });

  const session = useOrbitScanSession({
    router: queue.router,
    searchParams: queue.searchParams,
    orbitView: queue.orbitView,
    page: queue.page,
    pageSize: queue.pageSize,
    queryString: queue.queryString,
    queueSortDirection: queue.queueSortDirection,
    deferredSearch: queue.deferredSearch,
    bookmarks: queue.bookmarks,
    bookmarkById: queue.bookmarkById,
    queueIsLoading: queue.queueIsLoading,
    hasSearchQuery: queue.hasSearchQuery,
    highlightIdFromUrl: queue.highlightIdFromUrl,
    digestIdsFromUrl: queue.digestIdsFromUrl,
    sourceFromUrl: queue.sourceFromUrl,
    selectionMode,
    selectedBookmarkIds,
    setActiveBookmarkId,
  });

  const interactions = useOrbitPageInteractions({
    actions: queue.actions,
    scan: session.scan,
    tags: queue.tags,
    collections: queue.collections,
    bookmarks: queue.bookmarks,
    bookmarkById: queue.bookmarkById,
    orbitView: queue.orbitView,
    queueSortDirection: queue.queueSortDirection,
    page: queue.page,
    allQueueCountLabel: queue.allQueueCountLabel,
    hasSearchQuery: queue.hasSearchQuery,
    searchInputRef: queue.searchInputRef,
    scanTargetIds: session.scanTargetIds,
    reviewSession: session.reviewSession,
    activeBookmarkId,
    setActiveBookmarkId,
    selectionMode,
    setSelectionMode,
    selectedBookmarkIds,
    setSelectedBookmarkIds,
    setAppliedBookmarkIds: session.setAppliedBookmarkIds,
    handleScan: session.handleScan,
    handleOpenReviewAll: session.handleOpenReviewAll,
    handleOpenBookmarkReview: session.handleOpenBookmarkReview,
    handleKeepInOrbit: session.handleKeepInOrbit,
    handleAcceptSuggestion: session.handleAcceptSuggestion,
  });

  const selection = {
    mode: selectionMode,
    ids: selectedBookmarkIds,
    appliedIds: session.appliedBookmarkIds,
    toggleMode: interactions.toggleSelectionMode,
    onChange: interactions.handleSelectionChange,
    selectAllOnPage: interactions.handleSelectAllOnPage,
    bulkAddTag: interactions.handleBulkAddTag,
    bulkAddToCollection: interactions.handleBulkAddToCollection,
    bulkDelete: interactions.handleBulkDelete,
  };

  return {
    queue,
    session,
    interactions,
    selection,
    // Flat aliases — keep orbit-client stable during migration.
    router: queue.router,
    actions: queue.actions,
    createCollection: queue.createCollection,
    createCollectionQuick: queue.createCollectionQuick,
    scan: session.scan,
    tags: queue.tags,
    collections: queue.collections,
    libraryStats: queue.libraryStats,
    dbUser: queue.dbUser,
    bookmarks: queue.bookmarks,
    reviewBookmarks: session.reviewBookmarks,
    total: queue.total,
    totalPages: queue.totalPages,
    page: queue.page,
    orbitView: queue.orbitView,
    queueSortDirection: queue.queueSortDirection,
    search: queue.search,
    searchInputRef: queue.searchInputRef,
    selectionMode,
    selectedBookmarkIds,
    appliedBookmarkIds: session.appliedBookmarkIds,
    tagDialogOpen: interactions.tagDialogOpen,
    setTagDialogOpen: interactions.setTagDialogOpen,
    tagTargetIds: interactions.tagTargetIds,
    setTagTargetIds: interactions.setTagTargetIds,
    tagDialogBookmarks: interactions.tagDialogBookmarks,
    collectionDialogOpen: interactions.collectionDialogOpen,
    setCollectionDialogOpen: interactions.setCollectionDialogOpen,
    collectionTargetIds: interactions.collectionTargetIds,
    setCollectionTargetIds: interactions.setCollectionTargetIds,
    collectionDialogBookmarks: interactions.collectionDialogBookmarks,
    dialogTagIds: interactions.dialogTagIds,
    dialogCollectionIds: interactions.dialogCollectionIds,
    createCollectionOpen: interactions.createCollectionOpen,
    setCreateCollectionOpen: interactions.setCreateCollectionOpen,
    keyboardShortcutsOpen: interactions.keyboardShortcutsOpen,
    setKeyboardShortcutsOpen: interactions.setKeyboardShortcutsOpen,
    reviewSession: session.reviewSession,
    feedbackById: session.feedbackById,
    menuForId: interactions.menuForId,
    setMenuForId: interactions.setMenuForId,
    menuPosition: interactions.menuPosition,
    setMenuPosition: interactions.setMenuPosition,
    setActiveBookmarkId: interactions.setActiveBookmarkId,
    resolvedActiveBookmarkId: interactions.resolvedActiveBookmarkId,
    activeBookmark: interactions.activeBookmark,
    activeDecision: interactions.activeDecision,
    orbitOverlayOpen: interactions.orbitOverlayOpen,
    isLoading: queue.isLoading,
    isError: queue.isError,
    error: queue.error,
    refetch: queue.refetch,
    isFetching: queue.isFetching,
    isSearchPending: queue.isSearchPending,
    queueIsLoading: queue.queueIsLoading,
    scanHelperText: session.scanHelperText,
    scanButtonLabel: session.scanButtonLabel,
    triagedCount: session.triagedCount,
    passTotal: session.passTotal,
    activeScanPlanSuggestionCount: session.activeScanPlanSuggestionCount,
    scanTargetIds: session.scanTargetIds,
    scanTargetCount: session.scanTargetCount,
    selectedScanTargetIds: session.selectedScanTargetIds,
    resolvedScanBatchMode: session.resolvedScanBatchMode,
    scanBatchProfile: session.scanBatchProfile,
    scanBatchLimit: session.scanBatchLimit,
    deepUnlocked: session.deepUnlocked,
    deepLockedReason: session.deepLockedReason,
    canApplyStrongMatches: session.canApplyStrongMatches,
    canRescanCurrentSelection: session.canRescanCurrentSelection,
    staleScanPlan: session.staleScanPlan,
    hasSelectionOverflow: session.hasSelectionOverflow,
    lastScanRequest: session.lastScanRequest,
    orbitMapHref: interactions.orbitMapHref,
    visibleStatusLabel: interactions.visibleStatusLabel,
    setScanBatchMode: session.setScanBatchMode,
    goToTagOnDashboard: queue.goToTagOnDashboard,
    handleCreateCollectionOpen: interactions.handleCreateCollectionOpen,
    handleSyncComplete: queue.handleSyncComplete,
    handleOrbitViewChange: queue.handleOrbitViewChange,
    handleQueueSortDirectionChange: queue.handleQueueSortDirectionChange,
    handleSearchChange: queue.handleSearchChange,
    handlePageChange: queue.handlePageChange,
    handleScan: session.handleScan,
    handleRetryScan: session.handleRetryScan,
    handleRescanCurrentSelection: session.handleRescanCurrentSelection,
    handleApplyStrongMatches: session.handleApplyStrongMatches,
    handleOpenReviewAll: session.handleOpenReviewAll,
    handleClearScanPlan: session.handleClearScanPlan,
    handleOpenBookmarkReview: session.handleOpenBookmarkReview,
    handleReviewOpenChange: session.handleReviewOpenChange,
    handleApplyReviewedPlan: session.handleApplyReviewedPlan,
    handleKeepInOrbit: session.handleKeepInOrbit,
    handleAcceptSuggestion: session.handleAcceptSuggestion,
    handleOrbitOverlayDecision: interactions.handleOrbitOverlayDecision,
    handleMenuAction: interactions.handleMenuAction,
    handleBookmarkAddTag: interactions.handleBookmarkAddTag,
    handleBookmarkAddToCollection: interactions.handleBookmarkAddToCollection,
    toggleSelectionMode: interactions.toggleSelectionMode,
    handleSelectionChange: interactions.handleSelectionChange,
    handleSelectAllOnPage: interactions.handleSelectAllOnPage,
    handleBulkAddTag: interactions.handleBulkAddTag,
    handleBulkAddToCollection: interactions.handleBulkAddToCollection,
    handleBulkDelete: interactions.handleBulkDelete,
  };
}
