"use client";

import { useCallback, useState } from "react";

import { useOrbitPageInteractions } from "@/hooks/use-orbit-page-interactions";
import { useOrbitQueue } from "@/hooks/use-orbit-queue";
import { useOrbitScanSession } from "@/hooks/use-orbit-scan-session";

export type { BookmarkResponse, OrbitScanCandidatesResponse, OrbitScanRequest } from "@/lib/orbit-page-types";

export function useOrbitPage() {
  const [activeBookmarkId, setActiveBookmarkId] = useState<string | null>(null);
  const [selectionMode, setSelectionMode] = useState(false);
  const [selectedBookmarkIds, setSelectedBookmarkIds] = useState<Set<string>>(
    () => new Set()
  );

  const handleUrlStateApplied = useCallback(() => {
    setActiveBookmarkId(null);
    setSelectionMode(false);
    setSelectedBookmarkIds(new Set());
  }, []);

  const queue = useOrbitQueue({ onUrlStateApplied: handleUrlStateApplied });

  const scanSession = useOrbitScanSession({
    router: queue.router,
    searchParams: queue.searchParams,
    orbitView: queue.orbitView,
    page: queue.page,
    pageSize: queue.pageSize,
    queryString: queue.queryString,
    queueSortDirection: queue.queueSortDirection,
    deferredSearch: queue.deferredSearch,
    bookmarks: queue.bookmarks,
    bookmarkById: queue.bookmarkById,
    queueIsLoading: queue.queueIsLoading,
    hasSearchQuery: queue.hasSearchQuery,
    highlightIdFromUrl: queue.highlightIdFromUrl,
    digestIdsFromUrl: queue.digestIdsFromUrl,
    sourceFromUrl: queue.sourceFromUrl,
    selectionMode,
    selectedBookmarkIds,
    setActiveBookmarkId,
  });

  const interactions = useOrbitPageInteractions({
    actions: queue.actions,
    scan: scanSession.scan,
    tags: queue.tags,
    collections: queue.collections,
    bookmarks: queue.bookmarks,
    bookmarkById: queue.bookmarkById,
    orbitView: queue.orbitView,
    queueSortDirection: queue.queueSortDirection,
    page: queue.page,
    allQueueCountLabel: queue.allQueueCountLabel,
    hasSearchQuery: queue.hasSearchQuery,
    searchInputRef: queue.searchInputRef,
    scanTargetIds: scanSession.scanTargetIds,
    reviewSession: scanSession.reviewSession,
    activeBookmarkId,
    setActiveBookmarkId,
    selectionMode,
    setSelectionMode,
    selectedBookmarkIds,
    setSelectedBookmarkIds,
    setAppliedBookmarkIds: scanSession.setAppliedBookmarkIds,
    handleScan: scanSession.handleScan,
    handleOpenReviewAll: scanSession.handleOpenReviewAll,
    handleOpenBookmarkReview: scanSession.handleOpenBookmarkReview,
    handleKeepInOrbit: scanSession.handleKeepInOrbit,
    handleAcceptSuggestion: scanSession.handleAcceptSuggestion,
  });

  return {
    router: queue.router,
    actions: queue.actions,
    createCollection: queue.createCollection,
    createCollectionQuick: queue.createCollectionQuick,
    scan: scanSession.scan,
    tags: queue.tags,
    collections: queue.collections,
    dbUser: queue.dbUser,
    bookmarks: queue.bookmarks,
    reviewBookmarks: scanSession.reviewBookmarks,
    total: queue.total,
    totalPages: queue.totalPages,
    page: queue.page,
    orbitView: queue.orbitView,
    queueSortDirection: queue.queueSortDirection,
    search: queue.search,
    searchInputRef: queue.searchInputRef,
    selectionMode,
    selectedBookmarkIds,
    appliedBookmarkIds: scanSession.appliedBookmarkIds,
    tagDialogOpen: interactions.tagDialogOpen,
    setTagDialogOpen: interactions.setTagDialogOpen,
    tagTargetIds: interactions.tagTargetIds,
    setTagTargetIds: interactions.setTagTargetIds,
    tagDialogBookmarks: interactions.tagDialogBookmarks,
    collectionDialogOpen: interactions.collectionDialogOpen,
    setCollectionDialogOpen: interactions.setCollectionDialogOpen,
    collectionTargetIds: interactions.collectionTargetIds,
    setCollectionTargetIds: interactions.setCollectionTargetIds,
    collectionDialogBookmarks: interactions.collectionDialogBookmarks,
    dialogTagIds: interactions.dialogTagIds,
    dialogCollectionIds: interactions.dialogCollectionIds,
    createCollectionOpen: interactions.createCollectionOpen,
    setCreateCollectionOpen: interactions.setCreateCollectionOpen,
    keyboardShortcutsOpen: interactions.keyboardShortcutsOpen,
    setKeyboardShortcutsOpen: interactions.setKeyboardShortcutsOpen,
    reviewSession: scanSession.reviewSession,
    feedbackById: scanSession.feedbackById,
    menuForId: interactions.menuForId,
    setMenuForId: interactions.setMenuForId,
    menuPosition: interactions.menuPosition,
    setMenuPosition: interactions.setMenuPosition,
    setActiveBookmarkId: interactions.setActiveBookmarkId,
    resolvedActiveBookmarkId: interactions.resolvedActiveBookmarkId,
    activeBookmark: interactions.activeBookmark,
    activeDecision: interactions.activeDecision,
    orbitOverlayOpen: interactions.orbitOverlayOpen,
    isLoading: queue.isLoading,
    isError: queue.isError,
    error: queue.error,
    refetch: queue.refetch,
    isFetching: queue.isFetching,
    isSearchPending: queue.isSearchPending,
    queueIsLoading: queue.queueIsLoading,
    scanHelperText: scanSession.scanHelperText,
    scanButtonLabel: scanSession.scanButtonLabel,
    triagedCount: scanSession.triagedCount,
    passTotal: scanSession.passTotal,
    scanTargetIds: scanSession.scanTargetIds,
    scanTargetCount: scanSession.scanTargetCount,
    selectedScanTargetIds: scanSession.selectedScanTargetIds,
    resolvedScanBatchMode: scanSession.resolvedScanBatchMode,
    scanBatchProfile: scanSession.scanBatchProfile,
    scanBatchLimit: scanSession.scanBatchLimit,
    deepUnlocked: scanSession.deepUnlocked,
    deepLockedReason: scanSession.deepLockedReason,
    canApplyStrongMatches: scanSession.canApplyStrongMatches,
    canRescanCurrentSelection: scanSession.canRescanCurrentSelection,
    staleScanPlan: scanSession.staleScanPlan,
    hasSelectionOverflow: scanSession.hasSelectionOverflow,
    lastScanRequest: scanSession.lastScanRequest,
    orbitMapHref: interactions.orbitMapHref,
    visibleStatusLabel: interactions.visibleStatusLabel,
    setScanBatchMode: scanSession.setScanBatchMode,
    goToTagOnDashboard: queue.goToTagOnDashboard,
    handleCreateCollectionOpen: interactions.handleCreateCollectionOpen,
    handleSyncComplete: queue.handleSyncComplete,
    handleOrbitViewChange: queue.handleOrbitViewChange,
    handleQueueSortDirectionChange: queue.handleQueueSortDirectionChange,
    handleSearchChange: queue.handleSearchChange,
    handlePageChange: queue.handlePageChange,
    handleScan: scanSession.handleScan,
    handleRetryScan: scanSession.handleRetryScan,
    handleRescanCurrentSelection: scanSession.handleRescanCurrentSelection,
    handleApplyStrongMatches: scanSession.handleApplyStrongMatches,
    handleOpenReviewAll: scanSession.handleOpenReviewAll,
    handleClearScanPlan: scanSession.handleClearScanPlan,
    handleOpenBookmarkReview: scanSession.handleOpenBookmarkReview,
    handleReviewOpenChange: scanSession.handleReviewOpenChange,
    handleApplyReviewedPlan: scanSession.handleApplyReviewedPlan,
    handleKeepInOrbit: scanSession.handleKeepInOrbit,
    handleAcceptSuggestion: scanSession.handleAcceptSuggestion,
    handleOrbitOverlayDecision: interactions.handleOrbitOverlayDecision,
    handleMenuAction: interactions.handleMenuAction,
    handleBookmarkAddTag: interactions.handleBookmarkAddTag,
    handleBookmarkAddToCollection: interactions.handleBookmarkAddToCollection,
    toggleSelectionMode: interactions.toggleSelectionMode,
    handleSelectionChange: interactions.handleSelectionChange,
    handleSelectAllOnPage: interactions.handleSelectAllOnPage,
    handleBulkAddTag: interactions.handleBulkAddTag,
    handleBulkAddToCollection: interactions.handleBulkAddToCollection,
    handleBulkDelete: interactions.handleBulkDelete,
  };
}
